version: "3.9"

services:
  application:
    image: ghcr.io/alexbidenko/neural-translator/application:latest
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=/models/Llama-3.3-70B-Instruct-abliterated.safetensors
      - MAX_NEW_TOKENS=128
      - TEMPERATURE=0.7
      - TOP_P=0.9
    volumes:
      - /home/ubuntu/models:/models
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      # Для использования GPU:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
